// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_list_videos_response.proto

package com.x_keam.protobuff.model;

public final class PListVideosResponseOuterClass {
  private PListVideosResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PListVideosResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.x_keam.protobuff.model.PListVideosResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 response_code = 1;</code>
     */
    int getResponseCode();

    /**
     * <code>string response_message = 2;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string response_message = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    java.util.List<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo> 
        getVideosList();
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo getVideos(int index);
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    int getVideosCount();
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    java.util.List<? extends com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder> 
        getVideosOrBuilderList();
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder getVideosOrBuilder(
        int index);

    /**
     * <code>double last = 4;</code>
     */
    double getLast();
  }
  /**
   * Protobuf type {@code com.x_keam.protobuff.model.PListVideosResponse}
   */
  public  static final class PListVideosResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.x_keam.protobuff.model.PListVideosResponse)
      PListVideosResponseOrBuilder {
    // Use PListVideosResponse.newBuilder() to construct.
    private PListVideosResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PListVideosResponse() {
      responseCode_ = 0;
      responseMessage_ = "";
      videos_ = java.util.Collections.emptyList();
      last_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PListVideosResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              responseCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                videos_ = new java.util.ArrayList<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo>();
                mutable_bitField0_ |= 0x00000004;
              }
              videos_.add(
                  input.readMessage(com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.parser(), extensionRegistry));
              break;
            }
            case 33: {

              last_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          videos_ = java.util.Collections.unmodifiableList(videos_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.x_keam.protobuff.model.PListVideosResponseOuterClass.internal_static_com_x_keam_protobuff_model_PListVideosResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.x_keam.protobuff.model.PListVideosResponseOuterClass.internal_static_com_x_keam_protobuff_model_PListVideosResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.class, com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 response_code = 1;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int RESPONSE_MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string response_message = 2;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string response_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIDEOS_FIELD_NUMBER = 3;
    private java.util.List<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo> videos_;
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    public java.util.List<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo> getVideosList() {
      return videos_;
    }
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    public java.util.List<? extends com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder> 
        getVideosOrBuilderList() {
      return videos_;
    }
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    public int getVideosCount() {
      return videos_.size();
    }
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo getVideos(int index) {
      return videos_.get(index);
    }
    /**
     * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
     */
    public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder getVideosOrBuilder(
        int index) {
      return videos_.get(index);
    }

    public static final int LAST_FIELD_NUMBER = 4;
    private double last_;
    /**
     * <code>double last = 4;</code>
     */
    public double getLast() {
      return last_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCode_ != 0) {
        output.writeInt32(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMessage_);
      }
      for (int i = 0; i < videos_.size(); i++) {
        output.writeMessage(3, videos_.get(i));
      }
      if (last_ != 0D) {
        output.writeDouble(4, last_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMessage_);
      }
      for (int i = 0; i < videos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, videos_.get(i));
      }
      if (last_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, last_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse)) {
        return super.equals(obj);
      }
      com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse other = (com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse) obj;

      boolean result = true;
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && getVideosList()
          .equals(other.getVideosList());
      result = result && (
          java.lang.Double.doubleToLongBits(getLast())
          == java.lang.Double.doubleToLongBits(
              other.getLast()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + RESPONSE_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      if (getVideosCount() > 0) {
        hash = (37 * hash) + VIDEOS_FIELD_NUMBER;
        hash = (53 * hash) + getVideosList().hashCode();
      }
      hash = (37 * hash) + LAST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLast()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.x_keam.protobuff.model.PListVideosResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.x_keam.protobuff.model.PListVideosResponse)
        com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.x_keam.protobuff.model.PListVideosResponseOuterClass.internal_static_com_x_keam_protobuff_model_PListVideosResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.x_keam.protobuff.model.PListVideosResponseOuterClass.internal_static_com_x_keam_protobuff_model_PListVideosResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.class, com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.Builder.class);
      }

      // Construct using com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVideosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        responseCode_ = 0;

        responseMessage_ = "";

        if (videosBuilder_ == null) {
          videos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          videosBuilder_.clear();
        }
        last_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.x_keam.protobuff.model.PListVideosResponseOuterClass.internal_static_com_x_keam_protobuff_model_PListVideosResponse_descriptor;
      }

      public com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse getDefaultInstanceForType() {
        return com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.getDefaultInstance();
      }

      public com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse build() {
        com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse buildPartial() {
        com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse result = new com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.responseCode_ = responseCode_;
        result.responseMessage_ = responseMessage_;
        if (videosBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            videos_ = java.util.Collections.unmodifiableList(videos_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.videos_ = videos_;
        } else {
          result.videos_ = videosBuilder_.build();
        }
        result.last_ = last_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse) {
          return mergeFrom((com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse other) {
        if (other == com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse.getDefaultInstance()) return this;
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (videosBuilder_ == null) {
          if (!other.videos_.isEmpty()) {
            if (videos_.isEmpty()) {
              videos_ = other.videos_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureVideosIsMutable();
              videos_.addAll(other.videos_);
            }
            onChanged();
          }
        } else {
          if (!other.videos_.isEmpty()) {
            if (videosBuilder_.isEmpty()) {
              videosBuilder_.dispose();
              videosBuilder_ = null;
              videos_ = other.videos_;
              bitField0_ = (bitField0_ & ~0x00000004);
              videosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVideosFieldBuilder() : null;
            } else {
              videosBuilder_.addAllMessages(other.videos_);
            }
          }
        }
        if (other.getLast() != 0D) {
          setLast(other.getLast());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int responseCode_ ;
      /**
       * <code>int32 response_code = 1;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 response_code = 1;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 response_code = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string response_message = 2;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo> videos_ =
        java.util.Collections.emptyList();
      private void ensureVideosIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          videos_ = new java.util.ArrayList<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo>(videos_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder> videosBuilder_;

      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public java.util.List<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo> getVideosList() {
        if (videosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(videos_);
        } else {
          return videosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public int getVideosCount() {
        if (videosBuilder_ == null) {
          return videos_.size();
        } else {
          return videosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo getVideos(int index) {
        if (videosBuilder_ == null) {
          return videos_.get(index);
        } else {
          return videosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder setVideos(
          int index, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo value) {
        if (videosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVideosIsMutable();
          videos_.set(index, value);
          onChanged();
        } else {
          videosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder setVideos(
          int index, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder builderForValue) {
        if (videosBuilder_ == null) {
          ensureVideosIsMutable();
          videos_.set(index, builderForValue.build());
          onChanged();
        } else {
          videosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder addVideos(com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo value) {
        if (videosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVideosIsMutable();
          videos_.add(value);
          onChanged();
        } else {
          videosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder addVideos(
          int index, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo value) {
        if (videosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVideosIsMutable();
          videos_.add(index, value);
          onChanged();
        } else {
          videosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder addVideos(
          com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder builderForValue) {
        if (videosBuilder_ == null) {
          ensureVideosIsMutable();
          videos_.add(builderForValue.build());
          onChanged();
        } else {
          videosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder addVideos(
          int index, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder builderForValue) {
        if (videosBuilder_ == null) {
          ensureVideosIsMutable();
          videos_.add(index, builderForValue.build());
          onChanged();
        } else {
          videosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder addAllVideos(
          java.lang.Iterable<? extends com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo> values) {
        if (videosBuilder_ == null) {
          ensureVideosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, videos_);
          onChanged();
        } else {
          videosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder clearVideos() {
        if (videosBuilder_ == null) {
          videos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          videosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public Builder removeVideos(int index) {
        if (videosBuilder_ == null) {
          ensureVideosIsMutable();
          videos_.remove(index);
          onChanged();
        } else {
          videosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder getVideosBuilder(
          int index) {
        return getVideosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder getVideosOrBuilder(
          int index) {
        if (videosBuilder_ == null) {
          return videos_.get(index);  } else {
          return videosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public java.util.List<? extends com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder> 
           getVideosOrBuilderList() {
        if (videosBuilder_ != null) {
          return videosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(videos_);
        }
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder addVideosBuilder() {
        return getVideosFieldBuilder().addBuilder(
            com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder addVideosBuilder(
          int index) {
        return getVideosFieldBuilder().addBuilder(
            index, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.x_keam.protobuff.model.PVideoInfo videos = 3;</code>
       */
      public java.util.List<com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder> 
           getVideosBuilderList() {
        return getVideosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder> 
          getVideosFieldBuilder() {
        if (videosBuilder_ == null) {
          videosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder>(
                  videos_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          videos_ = null;
        }
        return videosBuilder_;
      }

      private double last_ ;
      /**
       * <code>double last = 4;</code>
       */
      public double getLast() {
        return last_;
      }
      /**
       * <code>double last = 4;</code>
       */
      public Builder setLast(double value) {
        
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double last = 4;</code>
       */
      public Builder clearLast() {
        
        last_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.x_keam.protobuff.model.PListVideosResponse)
    }

    // @@protoc_insertion_point(class_scope:com.x_keam.protobuff.model.PListVideosResponse)
    private static final com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse();
    }

    public static com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PListVideosResponse>
        PARSER = new com.google.protobuf.AbstractParser<PListVideosResponse>() {
      public PListVideosResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PListVideosResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PListVideosResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PListVideosResponse> getParserForType() {
      return PARSER;
    }

    public com.x_keam.protobuff.model.PListVideosResponseOuterClass.PListVideosResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_x_keam_protobuff_model_PListVideosResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_x_keam_protobuff_model_PListVideosResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034p_list_videos_response.proto\022\032com.x_ke" +
      "am.protobuff.model\032\022p_video_info.proto\"\214" +
      "\001\n\023PListVideosResponse\022\025\n\rresponse_code\030" +
      "\001 \001(\005\022\030\n\020response_message\030\002 \001(\t\0226\n\006video" +
      "s\030\003 \003(\0132&.com.x_keam.protobuff.model.PVi" +
      "deoInfo\022\014\n\004last\030\004 \001(\001B\034\n\032com.x_keam.prot" +
      "obuff.modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.x_keam.protobuff.model.PVideoInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_x_keam_protobuff_model_PListVideosResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_x_keam_protobuff_model_PListVideosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_x_keam_protobuff_model_PListVideosResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "ResponseMessage", "Videos", "Last", });
    com.x_keam.protobuff.model.PVideoInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
