// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_video_info.proto

package com.x_keam.protobuff.model;

public final class PVideoInfoOuterClass {
  private PVideoInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PVideoInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.x_keam.protobuff.model.PVideoInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 response_code = 1;</code>
     */
    int getResponseCode();

    /**
     * <code>string response_message = 2;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string response_message = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>string id = 3;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string image = 4;</code>
     */
    java.lang.String getImage();
    /**
     * <code>string image = 4;</code>
     */
    com.google.protobuf.ByteString
        getImageBytes();

    /**
     * <code>string title = 5;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 5;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string description = 6;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 6;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
     */
    boolean hasUser();
    /**
     * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
     */
    com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo getUser();
    /**
     * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
     */
    com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfoOrBuilder getUserOrBuilder();

    /**
     * <code>string md5 = 8;</code>
     */
    java.lang.String getMd5();
    /**
     * <code>string md5 = 8;</code>
     */
    com.google.protobuf.ByteString
        getMd5Bytes();

    /**
     * <code>int64 like_count = 9;</code>
     */
    long getLikeCount();

    /**
     * <code>int64 view_count = 10;</code>
     */
    long getViewCount();

    /**
     * <code>int64 time_stamp = 11;</code>
     */
    long getTimeStamp();
  }
  /**
   * Protobuf type {@code com.x_keam.protobuff.model.PVideoInfo}
   */
  public  static final class PVideoInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.x_keam.protobuff.model.PVideoInfo)
      PVideoInfoOrBuilder {
    // Use PVideoInfo.newBuilder() to construct.
    private PVideoInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PVideoInfo() {
      responseCode_ = 0;
      responseMessage_ = "";
      id_ = "";
      image_ = "";
      title_ = "";
      description_ = "";
      md5_ = "";
      likeCount_ = 0L;
      viewCount_ = 0L;
      timeStamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PVideoInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              responseCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              image_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 58: {
              com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              md5_ = s;
              break;
            }
            case 72: {

              likeCount_ = input.readInt64();
              break;
            }
            case 80: {

              viewCount_ = input.readInt64();
              break;
            }
            case 88: {

              timeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.x_keam.protobuff.model.PVideoInfoOuterClass.internal_static_com_x_keam_protobuff_model_PVideoInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.x_keam.protobuff.model.PVideoInfoOuterClass.internal_static_com_x_keam_protobuff_model_PVideoInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.class, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder.class);
    }

    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 response_code = 1;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int RESPONSE_MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string response_message = 2;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string response_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 3;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object image_;
    /**
     * <code>string image = 4;</code>
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      }
    }
    /**
     * <code>string image = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 5;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 5;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 6;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 7;
    private com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo user_;
    /**
     * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
     */
    public com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo getUser() {
      return user_ == null ? com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.getDefaultInstance() : user_;
    }
    /**
     * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
     */
    public com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfoOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int MD5_FIELD_NUMBER = 8;
    private volatile java.lang.Object md5_;
    /**
     * <code>string md5 = 8;</code>
     */
    public java.lang.String getMd5() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        md5_ = s;
        return s;
      }
    }
    /**
     * <code>string md5 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKE_COUNT_FIELD_NUMBER = 9;
    private long likeCount_;
    /**
     * <code>int64 like_count = 9;</code>
     */
    public long getLikeCount() {
      return likeCount_;
    }

    public static final int VIEW_COUNT_FIELD_NUMBER = 10;
    private long viewCount_;
    /**
     * <code>int64 view_count = 10;</code>
     */
    public long getViewCount() {
      return viewCount_;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 11;
    private long timeStamp_;
    /**
     * <code>int64 time_stamp = 11;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCode_ != 0) {
        output.writeInt32(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMessage_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
      }
      if (!getImageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, image_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, description_);
      }
      if (user_ != null) {
        output.writeMessage(7, getUser());
      }
      if (!getMd5Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, md5_);
      }
      if (likeCount_ != 0L) {
        output.writeInt64(9, likeCount_);
      }
      if (viewCount_ != 0L) {
        output.writeInt64(10, viewCount_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(11, timeStamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMessage_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
      }
      if (!getImageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, image_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, description_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getUser());
      }
      if (!getMd5Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, md5_);
      }
      if (likeCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, likeCount_);
      }
      if (viewCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, viewCount_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, timeStamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo)) {
        return super.equals(obj);
      }
      com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo other = (com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo) obj;

      boolean result = true;
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && getId()
          .equals(other.getId());
      result = result && getImage()
          .equals(other.getImage());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && getMd5()
          .equals(other.getMd5());
      result = result && (getLikeCount()
          == other.getLikeCount());
      result = result && (getViewCount()
          == other.getViewCount());
      result = result && (getTimeStamp()
          == other.getTimeStamp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + RESPONSE_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + MD5_FIELD_NUMBER;
      hash = (53 * hash) + getMd5().hashCode();
      hash = (37 * hash) + LIKE_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLikeCount());
      hash = (37 * hash) + VIEW_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getViewCount());
      hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.x_keam.protobuff.model.PVideoInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.x_keam.protobuff.model.PVideoInfo)
        com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.x_keam.protobuff.model.PVideoInfoOuterClass.internal_static_com_x_keam_protobuff_model_PVideoInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.x_keam.protobuff.model.PVideoInfoOuterClass.internal_static_com_x_keam_protobuff_model_PVideoInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.class, com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.Builder.class);
      }

      // Construct using com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseCode_ = 0;

        responseMessage_ = "";

        id_ = "";

        image_ = "";

        title_ = "";

        description_ = "";

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        md5_ = "";

        likeCount_ = 0L;

        viewCount_ = 0L;

        timeStamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.x_keam.protobuff.model.PVideoInfoOuterClass.internal_static_com_x_keam_protobuff_model_PVideoInfo_descriptor;
      }

      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo getDefaultInstanceForType() {
        return com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.getDefaultInstance();
      }

      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo build() {
        com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo buildPartial() {
        com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo result = new com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo(this);
        result.responseCode_ = responseCode_;
        result.responseMessage_ = responseMessage_;
        result.id_ = id_;
        result.image_ = image_;
        result.title_ = title_;
        result.description_ = description_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.md5_ = md5_;
        result.likeCount_ = likeCount_;
        result.viewCount_ = viewCount_;
        result.timeStamp_ = timeStamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo) {
          return mergeFrom((com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo other) {
        if (other == com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo.getDefaultInstance()) return this;
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getImage().isEmpty()) {
          image_ = other.image_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (!other.getMd5().isEmpty()) {
          md5_ = other.md5_;
          onChanged();
        }
        if (other.getLikeCount() != 0L) {
          setLikeCount(other.getLikeCount());
        }
        if (other.getViewCount() != 0L) {
          setViewCount(other.getViewCount());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 response_code = 1;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 response_code = 1;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 response_code = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string response_message = 2;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string response_message = 2;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 3;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 3;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object image_ = "";
      /**
       * <code>string image = 4;</code>
       */
      public java.lang.String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        java.lang.Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image = 4;</code>
       */
      public Builder setImage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image = 4;</code>
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      /**
       * <code>string image = 4;</code>
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        image_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 5;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 5;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 5;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 5;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 6;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo, com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.Builder, com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfoOrBuilder> userBuilder_;
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public Builder setUser(com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public Builder setUser(
          com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public Builder mergeUser(com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      public com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfoOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.com.x_keam.protobuff.model.PUserInfo user = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo, com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.Builder, com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfoOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo, com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfo.Builder, com.x_keam.protobuff.model.PUserInfoOuterClass.PUserInfoOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.lang.Object md5_ = "";
      /**
       * <code>string md5 = 8;</code>
       */
      public java.lang.String getMd5() {
        java.lang.Object ref = md5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          md5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string md5 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMd5Bytes() {
        java.lang.Object ref = md5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string md5 = 8;</code>
       */
      public Builder setMd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        md5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string md5 = 8;</code>
       */
      public Builder clearMd5() {
        
        md5_ = getDefaultInstance().getMd5();
        onChanged();
        return this;
      }
      /**
       * <code>string md5 = 8;</code>
       */
      public Builder setMd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        md5_ = value;
        onChanged();
        return this;
      }

      private long likeCount_ ;
      /**
       * <code>int64 like_count = 9;</code>
       */
      public long getLikeCount() {
        return likeCount_;
      }
      /**
       * <code>int64 like_count = 9;</code>
       */
      public Builder setLikeCount(long value) {
        
        likeCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 like_count = 9;</code>
       */
      public Builder clearLikeCount() {
        
        likeCount_ = 0L;
        onChanged();
        return this;
      }

      private long viewCount_ ;
      /**
       * <code>int64 view_count = 10;</code>
       */
      public long getViewCount() {
        return viewCount_;
      }
      /**
       * <code>int64 view_count = 10;</code>
       */
      public Builder setViewCount(long value) {
        
        viewCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 view_count = 10;</code>
       */
      public Builder clearViewCount() {
        
        viewCount_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>int64 time_stamp = 11;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 time_stamp = 11;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time_stamp = 11;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.x_keam.protobuff.model.PVideoInfo)
    }

    // @@protoc_insertion_point(class_scope:com.x_keam.protobuff.model.PVideoInfo)
    private static final com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo();
    }

    public static com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PVideoInfo>
        PARSER = new com.google.protobuf.AbstractParser<PVideoInfo>() {
      public PVideoInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PVideoInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PVideoInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PVideoInfo> getParserForType() {
      return PARSER;
    }

    public com.x_keam.protobuff.model.PVideoInfoOuterClass.PVideoInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_x_keam_protobuff_model_PVideoInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_x_keam_protobuff_model_PVideoInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022p_video_info.proto\022\032com.x_keam.protobu" +
      "ff.model\032\021p_user_info.proto\"\372\001\n\nPVideoIn" +
      "fo\022\025\n\rresponse_code\030\001 \001(\005\022\030\n\020response_me" +
      "ssage\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\022\r\n\005image\030\004 \001(\t\022\r" +
      "\n\005title\030\005 \001(\t\022\023\n\013description\030\006 \001(\t\0223\n\004us" +
      "er\030\007 \001(\0132%.com.x_keam.protobuff.model.PU" +
      "serInfo\022\013\n\003md5\030\010 \001(\t\022\022\n\nlike_count\030\t \001(\003" +
      "\022\022\n\nview_count\030\n \001(\003\022\022\n\ntime_stamp\030\013 \001(\003" +
      "B\034\n\032com.x_keam.protobuff.modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.x_keam.protobuff.model.PUserInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_x_keam_protobuff_model_PVideoInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_x_keam_protobuff_model_PVideoInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_x_keam_protobuff_model_PVideoInfo_descriptor,
        new java.lang.String[] { "ResponseCode", "ResponseMessage", "Id", "Image", "Title", "Description", "User", "Md5", "LikeCount", "ViewCount", "TimeStamp", });
    com.x_keam.protobuff.model.PUserInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
